# Generated by Django 5.2.1 on 2025-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_prediction_device_remove_prediction_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceip',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
